onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_fifo_swpb/bmp_code
add wave -noupdate /tb_fifo_swpb/bfOffBits
add wave -noupdate /tb_fifo_swpb/biWidth
add wave -noupdate /tb_fifo_swpb/biHeight
add wave -noupdate /tb_fifo_swpb/biBitCount
add wave -noupdate /tb_fifo_swpb/biSizeImage
add wave -noupdate /tb_fifo_swpb/clk
add wave -noupdate /tb_fifo_swpb/rst_n
add wave -noupdate /tb_fifo_swpb/s_axis_tdata
add wave -noupdate /tb_fifo_swpb/s_axis_tkeep
add wave -noupdate /tb_fifo_swpb/s_axis_tlast
add wave -noupdate /tb_fifo_swpb/s_axis_tvalid
add wave -noupdate /tb_fifo_swpb/s_axis_tready
add wave -noupdate /tb_fifo_swpb/x_coord
add wave -noupdate /tb_fifo_swpb/y_coord
add wave -noupdate /tb_fifo_swpb/o00
add wave -noupdate /tb_fifo_swpb/o01
add wave -noupdate /tb_fifo_swpb/o02
add wave -noupdate /tb_fifo_swpb/o03
add wave -noupdate /tb_fifo_swpb/o04
add wave -noupdate /tb_fifo_swpb/o05
add wave -noupdate /tb_fifo_swpb/o06
add wave -noupdate /tb_fifo_swpb/o10
add wave -noupdate /tb_fifo_swpb/o11
add wave -noupdate /tb_fifo_swpb/o12
add wave -noupdate /tb_fifo_swpb/o13
add wave -noupdate /tb_fifo_swpb/o14
add wave -noupdate /tb_fifo_swpb/o15
add wave -noupdate /tb_fifo_swpb/o16
add wave -noupdate /tb_fifo_swpb/o20
add wave -noupdate /tb_fifo_swpb/o21
add wave -noupdate /tb_fifo_swpb/o22
add wave -noupdate /tb_fifo_swpb/o23
add wave -noupdate /tb_fifo_swpb/o24
add wave -noupdate /tb_fifo_swpb/o25
add wave -noupdate /tb_fifo_swpb/o26
add wave -noupdate /tb_fifo_swpb/o30
add wave -noupdate /tb_fifo_swpb/o31
add wave -noupdate /tb_fifo_swpb/o32
add wave -noupdate /tb_fifo_swpb/o33
add wave -noupdate /tb_fifo_swpb/o34
add wave -noupdate /tb_fifo_swpb/o35
add wave -noupdate /tb_fifo_swpb/o36
add wave -noupdate /tb_fifo_swpb/o40
add wave -noupdate /tb_fifo_swpb/o41
add wave -noupdate /tb_fifo_swpb/o42
add wave -noupdate /tb_fifo_swpb/o43
add wave -noupdate /tb_fifo_swpb/o44
add wave -noupdate /tb_fifo_swpb/o45
add wave -noupdate /tb_fifo_swpb/o46
add wave -noupdate /tb_fifo_swpb/o50
add wave -noupdate /tb_fifo_swpb/o51
add wave -noupdate /tb_fifo_swpb/o52
add wave -noupdate /tb_fifo_swpb/o53
add wave -noupdate /tb_fifo_swpb/o54
add wave -noupdate /tb_fifo_swpb/o55
add wave -noupdate /tb_fifo_swpb/o56
add wave -noupdate /tb_fifo_swpb/o60
add wave -noupdate /tb_fifo_swpb/o61
add wave -noupdate /tb_fifo_swpb/o62
add wave -noupdate /tb_fifo_swpb/o63
add wave -noupdate /tb_fifo_swpb/o64
add wave -noupdate /tb_fifo_swpb/o65
add wave -noupdate /tb_fifo_swpb/o66
add wave -noupdate /tb_fifo_swpb/o70
add wave -noupdate /tb_fifo_swpb/o71
add wave -noupdate /tb_fifo_swpb/o72
add wave -noupdate /tb_fifo_swpb/o73
add wave -noupdate /tb_fifo_swpb/o74
add wave -noupdate /tb_fifo_swpb/o75
add wave -noupdate /tb_fifo_swpb/o76
add wave -noupdate /tb_fifo_swpb/xy_coord_vld
add wave -noupdate /tb_fifo_swpb/score_eol
add wave -noupdate /tb_fifo_swpb/patch8x7_valid
add wave -noupdate /tb_fifo_swpb/c
add wave -noupdate /tb_fifo_swpb/r
add wave -noupdate /tb_fifo_swpb/swpb_03_47
add wave -noupdate /glbl/GSR
add wave -noupdate /tb_fifo_swpb/biHeight
add wave -noupdate /tb_fifo_swpb/biWidth
add wave -noupdate /tb_fifo_swpb/c
add wave -noupdate /tb_fifo_swpb/r
add wave -noupdate /tb_fifo_swpb/s_axis_tdata
add wave -noupdate /tb_fifo_swpb/s_axis_tkeep
add wave -noupdate /tb_fifo_swpb/s_axis_tlast
add wave -noupdate /tb_fifo_swpb/s_axis_tready
add wave -noupdate /tb_fifo_swpb/s_axis_tvalid
add wave -noupdate /tb_fifo_swpb/x_coord
add wave -noupdate /tb_fifo_swpb/xy_coord_vld
add wave -noupdate /tb_fifo_swpb/y_coord
add wave -noupdate /tb_fifo_swpb/clk
add wave -noupdate /tb_fifo_swpb/o00
add wave -noupdate /tb_fifo_swpb/o01
add wave -noupdate /tb_fifo_swpb/o02
add wave -noupdate /tb_fifo_swpb/o03
add wave -noupdate /tb_fifo_swpb/o04
add wave -noupdate /tb_fifo_swpb/o05
add wave -noupdate /tb_fifo_swpb/o06
add wave -noupdate /tb_fifo_swpb/o10
add wave -noupdate /tb_fifo_swpb/o11
add wave -noupdate /tb_fifo_swpb/o12
add wave -noupdate /tb_fifo_swpb/o13
add wave -noupdate /tb_fifo_swpb/o14
add wave -noupdate /tb_fifo_swpb/o15
add wave -noupdate /tb_fifo_swpb/o16
add wave -noupdate /tb_fifo_swpb/o20
add wave -noupdate /tb_fifo_swpb/o21
add wave -noupdate /tb_fifo_swpb/o22
add wave -noupdate /tb_fifo_swpb/o23
add wave -noupdate /tb_fifo_swpb/o24
add wave -noupdate /tb_fifo_swpb/o25
add wave -noupdate /tb_fifo_swpb/o26
add wave -noupdate /tb_fifo_swpb/o30
add wave -noupdate /tb_fifo_swpb/o31
add wave -noupdate /tb_fifo_swpb/o32
add wave -noupdate /tb_fifo_swpb/o33
add wave -noupdate /tb_fifo_swpb/o34
add wave -noupdate /tb_fifo_swpb/o35
add wave -noupdate /tb_fifo_swpb/o36
add wave -noupdate /tb_fifo_swpb/o40
add wave -noupdate /tb_fifo_swpb/o41
add wave -noupdate /tb_fifo_swpb/o42
add wave -noupdate /tb_fifo_swpb/o43
add wave -noupdate /tb_fifo_swpb/o44
add wave -noupdate /tb_fifo_swpb/o45
add wave -noupdate /tb_fifo_swpb/o46
add wave -noupdate /tb_fifo_swpb/o50
add wave -noupdate /tb_fifo_swpb/o51
add wave -noupdate /tb_fifo_swpb/o52
add wave -noupdate /tb_fifo_swpb/o53
add wave -noupdate /tb_fifo_swpb/o54
add wave -noupdate /tb_fifo_swpb/o55
add wave -noupdate /tb_fifo_swpb/o56
add wave -noupdate /tb_fifo_swpb/o60
add wave -noupdate /tb_fifo_swpb/o61
add wave -noupdate /tb_fifo_swpb/o62
add wave -noupdate /tb_fifo_swpb/o63
add wave -noupdate /tb_fifo_swpb/o64
add wave -noupdate /tb_fifo_swpb/o65
add wave -noupdate /tb_fifo_swpb/o66
add wave -noupdate /tb_fifo_swpb/o70
add wave -noupdate /tb_fifo_swpb/o71
add wave -noupdate /tb_fifo_swpb/o72
add wave -noupdate /tb_fifo_swpb/o73
add wave -noupdate /tb_fifo_swpb/o74
add wave -noupdate /tb_fifo_swpb/o75
add wave -noupdate /tb_fifo_swpb/o76
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {999050 ps} {1000050 ps}
