onerror {resume}
quietly virtual signal -install /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo { (concat_noflatten) (context /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo )&{o06 , o05 , o04 , o03 , o02 , o01 , o00 }} line_1_7patch
quietly virtual signal -install /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo { (concat_noflatten) (context /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo )&{o16 , o15 , o14 , o13 , o12 , o11 , o10 }} line_2_7patch
quietly virtual signal -install /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo { (concat_noflatten) (context /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo )&{o26 , o25 , o24 , o23 , o22 , o21 , o20 }} line_3_7patch
quietly virtual signal -install /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo { (concat_noflatten) (context /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo )&{o36 , o35 , o34 , o33 , o32 , o31 , o30 }} line_4_7patch
quietly virtual signal -install /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo { (concat_noflatten) (context /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo )&{o46 , o45 , o44 , o43 , o42 , o41 , o40 }} line_5_7patch
quietly virtual signal -install /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo { (concat_noflatten) (context /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo )&{o50 , o51 , o52 , o53 , o54 , o55 , o56 }} line_6_7patch
quietly virtual signal -install /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo { (concat_noflatten) (context /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo )&{o66 , o65 , o64 , o63 , o62 , o61 , o60 }} line_7_7patch
quietly virtual signal -install /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder { (concat_noflatten) (context /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder )&{in15 , in14 , in13 , in12 , in11 , in10 , in9 , in8 , in7 , in6 , in5 , in4 , in3 , in2 , in1 , in0 }} ring_pixels
quietly virtual signal -install /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder { (concat_noflatten) (context /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder )&{in0 , in1 , in2 , in3 , in4 , in5 , in6 , in7 , in8 , in9 , in10 , in11 , in12 , in13 , in14 , in15 }} ring_pixel
quietly virtual function -install /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder -env /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder { (concat_noflatten)(concat_flatten)&{/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o0b, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o1b, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o2b, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o3b, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o4b, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o5b, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o6b, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o7b, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o8b, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o9b, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o10b, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o11b, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o12b, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o13b, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o14b, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o15b }} output_diff_brightpixel
quietly virtual function -install /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder -env /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder { (concat_noflatten)(concat_flatten)&{/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o0d, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o1d, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o2d, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o3d, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o4d, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o5d, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o6d, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o7d, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o8d, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o9d, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o10d, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o11d, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o12d, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o13d, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o14d, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o15d }} output_diff_darkpixel
quietly virtual function -install /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder -env /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder { (concat_noflatten)(concat_flatten)&{/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr0, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr1, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr2, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr3, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr4, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr5, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr6, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr7, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr8, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr9, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr10, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr11, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr12, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr13, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr14, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr15 }} first_clk_cmr
quietly virtual function -install /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder -env /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder { (concat_noflatten)(concat_flatten)&{/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc0, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc1, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc2, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc3, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc4, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc5, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc6, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc7, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc8, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc9, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc10, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc11, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc12, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc13, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc14, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc15 }} first_clk_rmc
quietly virtual function -install /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder -env /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder { (concat_noflatten)(concat_flatten)&{/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr0t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr1t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr2t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr3t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr4t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr5t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr6t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr7t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr8t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr9t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr10t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr11t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr12t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr13t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr14t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr15t }} 2rd_clk_cmr_t
quietly virtual function -install /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder -env /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder { (concat_noflatten)(concat_flatten)&{/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc0t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc1t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc2t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc3t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc4t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc5t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc6t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc7t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc8t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc9t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc10t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc11t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc12t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc13t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc14t, /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc15t }} 2rd_clk_rmc_t
quietly virtual signal -install /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score { (concat_noflatten) (context /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score )&{i0b , i1b , i2b , i3b , i4b , i5b , i6b , i7b , i8b , i9b , i10b , i11b , i12b , i13b , i14b , i15b }} diff_rmc_t
quietly virtual signal -install /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score { (concat_noflatten) (context /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score )&{i0d , i1d , i2d , i3d , i4d , i5d , i6d , i7d , i8d , i9d , i10d , i11d , i12d , i13d , i14d , i15d }} diff_cmr_t
quietly virtual function -install /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score -env /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score { (concat_noflatten)(concat_flatten)&{/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/s0b, /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/s1b, /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/s2b, /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/s3b, /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/s4b, /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/s5b, /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/s6b, /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/s7b }} 1st_clk_compute_ixb_ixd
quietly virtual function -install /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score -env /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score { (concat_noflatten)(concat_flatten)&{/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/ss0b, /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/ss1b, /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/ss2b, /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/ss3b }} 2nd_clk_compute
quietly virtual function -install /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score -env /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score { (concat_noflatten)(concat_flatten)&{/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/sss0b, /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/sss1b }} 3rd_clk_compute_ixb
quietly virtual function -install /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score -env /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score { (concat_noflatten)(concat_flatten)&{/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/s0d, /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/s1d, /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/s2d, /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/s3d, /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/s4d, /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/s5d, /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/s6d, /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/s7d }} 1st_clk_compute_ixd
quietly virtual function -install /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score -env /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score { (concat_noflatten)(concat_flatten)&{/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/ss0d, /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/ss1d, /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/ss2d, /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/ss3d }} 2nd_clk_compute_ixd
quietly virtual function -install /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score -env /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score { (concat_noflatten)(concat_flatten)&{/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/sss0d, /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/sss1d }} 3rd_clk_compute_ixd
quietly virtual function -install /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo -env /tb { (concat_noflatten)(concat_flatten)(concat_reverse)&{/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/ram_0 }} ram0
quietly virtual function -install /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo -env /tb { (concat_noflatten)(concat_flatten)(concat_reverse)&{/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/ram_1 }} ram1
quietly virtual function -install /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo -env /tb { (concat_noflatten)(concat_flatten)(concat_reverse)&{/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/ram_2 }} ram2
quietly virtual function -install /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo -env /tb { (concat_noflatten)(concat_flatten)(concat_reverse)&{/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/ram_3 }} ram3
quietly virtual function -install /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo -env /tb { (concat_noflatten)(concat_flatten)(concat_reverse)&{/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/ram_4 }} ram4
quietly virtual function -install /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo -env /tb { (concat_noflatten)(concat_flatten)(concat_reverse)&{/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/ram_5 }} ram5
quietly virtual signal -install /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo { /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/xy_coord_tmp[19:10]} xy_coord_tmp_x_coord
quietly virtual signal -install /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo { /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/xy_coord_tmp[9:0]} xy_coord_tmp_y_coord
quietly virtual signal -install /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo { /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/xy_coord[19:10]} xy_coord_x_coord
quietly virtual signal -install /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo { /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/xy_coord[9:0]} xy_coord_y_coord
quietly virtual signal -install /tb/u_FAST_with_NMS/u_NMS_top { (concat_noflatten) (context /tb/u_FAST_with_NMS/u_NMS_top )&{int11[0] , int11[1] , int11[2] , int11[3] , int11[4] , int11[5] , int11[6] , int11[7] , int11[8] , int11[9] , int11[10] , int11[11] , int11[12] , int11[13] , int11[14] , int11[15] , int11[16] , int11[17] , int11[18] , int11[19] , int11[20] , int11[21] , int11[22] , int11[23] , int11[24] , int11[25] , int11[26] , int11[27] , int11[28] , int11[29] , int11[30] , int11[31] , int11[32] , int11[33] , int12[0] , int12[1] , int12[2] , int12[3] , int12[4] , int12[5] , int12[6] , int12[7] , int12[8] , int12[9] , int12[10] , int12[11] , int12[12] , int12[13] , int12[14] , int12[15] , int12[16] , int12[17] , int12[18] , int12[19] , int12[20] , int12[21] , int12[22] , int12[23] , int12[24] , int12[25] , int12[26] , int12[27] , int12[28] , int12[29] , int12[30] , int12[31] , int12[32] , int12[33] , int13[0] , int13[1] , int13[2] , int13[3] , int13[4] , int13[5] , int13[6] , int13[7] , int13[8] , int13[9] , int13[10] , int13[11] , int13[12] , int13[13] , int13[14] , int13[15] , int13[16] , int13[17] , int13[18] , int13[19] , int13[20] , int13[21] , int13[22] , int13[23] , int13[24] , int13[25] , int13[26] , int13[27] , int13[28] , int13[29] , int13[30] , int13[31] , int13[32] , int13[33] }} nms_patch_1st_line
quietly virtual signal -install /tb/u_FAST_with_NMS/u_NMS_top { (concat_noflatten) (context /tb/u_FAST_with_NMS/u_NMS_top )&{int11[0] , int11[1] , int11[2] , int11[3] , int11[4] , int11[5] , int11[6] , int11[7] , int11[8] , int11[9] , int11[10] , int11[11] , int11[12] , int11[13] , int11[14] , int11[15] , int11[16] , int11[17] , int11[18] , int11[19] , int11[20] , int11[21] , int11[22] , int11[23] , int11[24] , int11[25] , int11[26] , int11[27] , int11[28] , int11[29] , int11[30] , int11[31] , int11[32] , int11[33] , int12[0] , int12[1] , int12[2] , int12[3] , int12[4] , int12[5] , int12[6] , int12[7] , int12[8] , int12[9] , int12[10] , int12[11] , int12[12] , int12[13] , int12[14] , int12[15] , int12[16] , int12[17] , int12[18] , int12[19] , int12[20] , int12[21] , int12[22] , int12[23] , int12[24] , int12[25] , int12[26] , int12[27] , int12[28] , int12[29] , int12[30] , int12[31] , int12[32] , int12[33] , int13[0] , int13[1] , int13[2] , int13[3] , int13[4] , int13[5] , int13[6] , int13[7] , int13[8] , int13[9] , int13[10] , int13[11] , int13[12] , int13[13] , int13[14] , int13[15] , int13[16] , int13[17] , int13[18] , int13[19] , int13[20] , int13[21] , int13[22] , int13[23] , int13[24] , int13[25] , int13[26] , int13[27] , int13[28] , int13[29] , int13[30] , int13[31] , int13[32] , int13[33] }} 1st_line_nms_patch
quietly virtual signal -install /tb/u_FAST_with_NMS/u_NMS_top { (concat_noflatten) (context /tb/u_FAST_with_NMS/u_NMS_top )&{int11 , int12 , int13 }} 1st_line
quietly virtual signal -install /tb/u_FAST_with_NMS/u_NMS_top { (concat_noflatten) (context /tb/u_FAST_with_NMS/u_NMS_top )&{int11 , int12 , int13 }} 2nd_line
quietly virtual signal -install /tb/u_FAST_with_NMS/u_NMS_top { (concat_noflatten) (context /tb/u_FAST_with_NMS/u_NMS_top )&{int21 , int22 , int23 }} 2nd_line_nms_patch
quietly virtual signal -install /tb/u_FAST_with_NMS/u_NMS_top { (concat_noflatten) (context /tb/u_FAST_with_NMS/u_NMS_top )&{int31 , int32 , int33 }} 3rd_line_nms_patch
quietly WaveActivateNextPane {} 0
add wave -noupdate -group fast_fifo /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/data_in
add wave -noupdate -group fast_fifo -color Coral /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/clk
add wave -noupdate -group fast_fifo /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/rst
add wave -noupdate -group fast_fifo /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/ce
add wave -noupdate -group fast_fifo -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/x_coord
add wave -noupdate -group fast_fifo -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/y_coord
add wave -noupdate -group fast_fifo -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/xy_coord_x_coord
add wave -noupdate -group fast_fifo -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/xy_coord_y_coord
add wave -noupdate -group fast_fifo -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/xy_coord
add wave -noupdate -group fast_fifo /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/line_1_7patch
add wave -noupdate -group fast_fifo /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/line_2_7patch
add wave -noupdate -group fast_fifo /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/line_3_7patch
add wave -noupdate -group fast_fifo /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/line_4_7patch
add wave -noupdate -group fast_fifo /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/line_5_7patch
add wave -noupdate -group fast_fifo /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/line_6_7patch
add wave -noupdate -group fast_fifo /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/line_7_7patch
add wave -noupdate -group fast_fifo -color Pink /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/patch_7x7_vld
add wave -noupdate -group fast_fifo -color {Violet Red} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/xy_coord_vld
add wave -noupdate -group fast_fifo -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/address_read
add wave -noupdate -group fast_fifo -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/address_write
add wave -noupdate -group fast_fifo /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/data_out_0
add wave -noupdate -group fast_fifo /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/data_out_1
add wave -noupdate -group fast_fifo /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/data_out_2
add wave -noupdate -group fast_fifo /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/data_out_3
add wave -noupdate -group fast_fifo /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/data_out_4
add wave -noupdate -group fast_fifo /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/data_out_5
add wave -noupdate -group fast_fifo /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/ram0
add wave -noupdate -group fast_fifo /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/ram1
add wave -noupdate -group fast_fifo /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/ram2
add wave -noupdate -group fast_fifo /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/ram3
add wave -noupdate -group fast_fifo /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/ram4
add wave -noupdate -group fast_fifo /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/ram5
add wave -noupdate -group fast_fifo -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/cnt_row
add wave -noupdate -group fast_fifo -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/cnt_row_d
add wave -noupdate -group fast_fifo -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/xy_coord_tmp_x_coord
add wave -noupdate -group fast_fifo -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/xy_coord_tmp_y_coord
add wave -noupdate -group fast_fifo /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/xy_coord_tmp
add wave -noupdate -group fast_fifo /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/EOL
add wave -noupdate -group fast_diff_center_ring -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/THRESHOLD
add wave -noupdate -group fast_diff_center_ring -color Coral /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/clk
add wave -noupdate -group fast_diff_center_ring /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/rst
add wave -noupdate -group fast_diff_center_ring /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/ce
add wave -noupdate -group fast_diff_center_ring -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/line_1_7patch
add wave -noupdate -group fast_diff_center_ring -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/line_2_7patch
add wave -noupdate -group fast_diff_center_ring -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/line_3_7patch
add wave -noupdate -group fast_diff_center_ring -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/line_4_7patch
add wave -noupdate -group fast_diff_center_ring -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/line_5_7patch
add wave -noupdate -group fast_diff_center_ring -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/line_6_7patch
add wave -noupdate -group fast_diff_center_ring -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/line_7_7patch
add wave -noupdate -group fast_diff_center_ring -color Pink /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/patch_7x7_vld
add wave -noupdate -group fast_diff_center_ring -color {Violet Red} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/xy_coord_vld
add wave -noupdate -group fast_diff_center_ring -radix unsigned -childformat {{/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/ring_pixel.in0 -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/ring_pixel.in1 -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/ring_pixel.in2 -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/ring_pixel.in3 -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/ring_pixel.in4 -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/ring_pixel.in5 -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/ring_pixel.in6 -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/ring_pixel.in7 -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/ring_pixel.in8 -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/ring_pixel.in9 -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/ring_pixel.in10 -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/ring_pixel.in11 -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/ring_pixel.in12 -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/ring_pixel.in13 -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/ring_pixel.in14 -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/ring_pixel.in15 -radix unsigned}} -subitemconfig {/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/in0 {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/in1 {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/in2 {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/in3 {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/in4 {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/in5 {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/in6 {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/in7 {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/in8 {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/in9 {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/in10 {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/in11 {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/in12 {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/in13 {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/in14 {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/in15 {-radix unsigned}} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/ring_pixel
add wave -noupdate -group fast_diff_center_ring -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/center
add wave -noupdate -group fast_diff_center_ring -radix binary /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/bright
add wave -noupdate -group fast_diff_center_ring -radix binary /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/dark
add wave -noupdate -group fast_diff_center_ring -radix decimal -childformat {{cmr0 -radix decimal} {cmr1 -radix decimal} {cmr2 -radix decimal} {cmr3 -radix decimal} {cmr4 -radix decimal} {cmr5 -radix decimal} {cmr6 -radix decimal} {cmr7 -radix decimal} {cmr8 -radix decimal} {cmr9 -radix decimal} {cmr10 -radix decimal} {cmr11 -radix decimal} {cmr12 -radix decimal} {cmr13 -radix decimal} {cmr14 -radix decimal} {cmr15 -radix decimal}} -subitemconfig {/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr0 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr1 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr2 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr3 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr4 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr5 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr6 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr7 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr8 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr9 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr10 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr11 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr12 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr13 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr14 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr15 {-radix decimal}} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/first_clk_cmr
add wave -noupdate -group fast_diff_center_ring -radix decimal -childformat {{rmc0 -radix decimal} {rmc1 -radix decimal} {rmc2 -radix decimal} {rmc3 -radix decimal} {rmc4 -radix decimal} {rmc5 -radix decimal} {rmc6 -radix decimal} {rmc7 -radix decimal} {rmc8 -radix decimal} {rmc9 -radix decimal} {rmc10 -radix decimal} {rmc11 -radix decimal} {rmc12 -radix decimal} {rmc13 -radix decimal} {rmc14 -radix decimal} {rmc15 -radix decimal}} -subitemconfig {/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc0 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc1 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc2 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc3 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc4 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc5 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc6 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc7 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc8 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc9 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc10 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc11 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc12 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc13 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc14 {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc15 {-radix decimal}} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/first_clk_rmc
add wave -noupdate -group fast_diff_center_ring -radix decimal -childformat {{cmr0t -radix decimal} {cmr1t -radix decimal} {cmr2t -radix decimal} {cmr3t -radix decimal} {cmr4t -radix decimal} {cmr5t -radix decimal} {cmr6t -radix decimal} {cmr7t -radix decimal} {cmr8t -radix decimal} {cmr9t -radix decimal} {cmr10t -radix decimal} {cmr11t -radix decimal} {cmr12t -radix decimal} {cmr13t -radix decimal} {cmr14t -radix decimal} {cmr15t -radix decimal}} -subitemconfig {/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr0t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr1t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr2t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr3t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr4t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr5t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr6t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr7t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr8t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr9t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr10t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr11t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr12t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr13t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr14t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/cmr15t {-radix decimal}} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/2rd_clk_cmr_t
add wave -noupdate -group fast_diff_center_ring -radix decimal -childformat {{rmc0t -radix decimal} {rmc1t -radix decimal} {rmc2t -radix decimal} {rmc3t -radix decimal} {rmc4t -radix decimal} {rmc5t -radix decimal} {rmc6t -radix decimal} {rmc7t -radix decimal} {rmc8t -radix decimal} {rmc9t -radix decimal} {rmc10t -radix decimal} {rmc11t -radix decimal} {rmc12t -radix decimal} {rmc13t -radix decimal} {rmc14t -radix decimal} {rmc15t -radix decimal}} -subitemconfig {/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc0t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc1t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc2t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc3t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc4t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc5t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc6t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc7t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc8t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc9t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc10t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc11t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc12t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc13t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc14t {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/rmc15t {-radix decimal}} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/2rd_clk_rmc_t
add wave -noupdate -group fast_diff_center_ring -radix decimal -childformat {{o0b -radix decimal} {o1b -radix decimal} {o2b -radix decimal} {o3b -radix decimal} {o4b -radix decimal} {o5b -radix decimal} {o6b -radix decimal} {o7b -radix decimal} {o8b -radix decimal} {o9b -radix decimal} {o10b -radix decimal} {o11b -radix decimal} {o12b -radix decimal} {o13b -radix decimal} {o14b -radix decimal} {o15b -radix decimal}} -subitemconfig {/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o0b {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o1b {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o2b {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o3b {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o4b {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o5b {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o6b {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o7b {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o8b {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o9b {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o10b {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o11b {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o12b {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o13b {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o14b {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o15b {-radix decimal}} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/output_diff_brightpixel
add wave -noupdate -group fast_diff_center_ring -radix decimal -childformat {{o0d -radix decimal} {o1d -radix decimal} {o2d -radix decimal} {o3d -radix decimal} {o4d -radix decimal} {o5d -radix decimal} {o6d -radix decimal} {o7d -radix decimal} {o8d -radix decimal} {o9d -radix decimal} {o10d -radix decimal} {o11d -radix decimal} {o12d -radix decimal} {o13d -radix decimal} {o14d -radix decimal} {o15d -radix decimal}} -subitemconfig {/tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o0d {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o1d {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o2d {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o3d {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o4d {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o5d {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o6d {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o7d {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o8d {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o9d {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o10d {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o11d {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o12d {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o13d {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o14d {-radix decimal} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/o15d {-radix decimal}} /tb/u_FAST_with_NMS/u_fast_main_top/u_thresholder/output_diff_darkpixel
add wave -noupdate -group check_contiguity -color Orange /tb/u_FAST_with_NMS/u_fast_main_top/u_contig_processor/clk
add wave -noupdate -group check_contiguity /tb/u_FAST_with_NMS/u_fast_main_top/u_contig_processor/rst
add wave -noupdate -group check_contiguity /tb/u_FAST_with_NMS/u_fast_main_top/u_contig_processor/ce
add wave -noupdate -group check_contiguity -color Pink /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/patch_7x7_vld
add wave -noupdate -group check_contiguity -color {Violet Red} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/xy_coord_vld
add wave -noupdate -group check_contiguity -radix binary /tb/u_FAST_with_NMS/u_fast_main_top/u_contig_processor/input_d
add wave -noupdate -group check_contiguity -radix binary /tb/u_FAST_with_NMS/u_fast_main_top/u_contig_processor/input_b
add wave -noupdate -group check_contiguity -color {Medium Aquamarine} /tb/u_FAST_with_NMS/u_fast_main_top/u_contig_processor/contig
add wave -noupdate -group check_contiguity -color {Sky Blue} /tb/u_FAST_with_NMS/u_fast_main_top/u_contig_processor/contig_d
add wave -noupdate -group check_contiguity -color {Light Blue} /tb/u_FAST_with_NMS/u_fast_main_top/u_contig_processor/contig_d1
add wave -noupdate -group check_contiguity -color {Light Steel Blue} /tb/u_FAST_with_NMS/u_fast_main_top/u_contig_processor/contig_d2
add wave -noupdate -group check_contiguity -color {Steel Blue} /tb/u_FAST_with_NMS/u_fast_main_top/u_contig_processor/contig_d3
add wave -noupdate -group check_contiguity /tb/u_FAST_with_NMS/u_fast_main_top/u_contig_processor/contig_b
add wave -noupdate -group compute_score -color Orange /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/clk
add wave -noupdate -group compute_score /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/rst
add wave -noupdate -group compute_score /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/ce
add wave -noupdate -group compute_score -color Pink /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/patch_7x7_vld
add wave -noupdate -group compute_score -color {Violet Red} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/xy_coord_vld
add wave -noupdate -group compute_score -radix unsigned -childformat {{/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_rmc_t.i0b -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_rmc_t.i1b -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_rmc_t.i2b -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_rmc_t.i3b -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_rmc_t.i4b -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_rmc_t.i5b -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_rmc_t.i6b -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_rmc_t.i7b -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_rmc_t.i8b -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_rmc_t.i9b -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_rmc_t.i10b -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_rmc_t.i11b -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_rmc_t.i12b -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_rmc_t.i13b -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_rmc_t.i14b -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_rmc_t.i15b -radix unsigned}} -subitemconfig {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i0b {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i1b {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i2b {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i3b {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i4b {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i5b {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i6b {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i7b {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i8b {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i9b {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i10b {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i11b {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i12b {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i13b {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i14b {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i15b {-radix unsigned}} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_rmc_t
add wave -noupdate -group compute_score -radix unsigned -childformat {{/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_cmr_t.i0d -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_cmr_t.i1d -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_cmr_t.i2d -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_cmr_t.i3d -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_cmr_t.i4d -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_cmr_t.i5d -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_cmr_t.i6d -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_cmr_t.i7d -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_cmr_t.i8d -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_cmr_t.i9d -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_cmr_t.i10d -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_cmr_t.i11d -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_cmr_t.i12d -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_cmr_t.i13d -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_cmr_t.i14d -radix unsigned} {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_cmr_t.i15d -radix unsigned}} -subitemconfig {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i0d {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i1d {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i2d {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i3d {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i4d {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i5d {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i6d {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i7d {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i8d {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i9d {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i10d {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i11d {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i12d {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i13d {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i14d {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/i15d {-radix unsigned}} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/diff_cmr_t
add wave -noupdate -group compute_score -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/score
add wave -noupdate -group compute_score -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/1st_clk_compute_ixb_ixd
add wave -noupdate -group compute_score -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/2nd_clk_compute
add wave -noupdate -group compute_score -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/3rd_clk_compute_ixb
add wave -noupdate -group compute_score -radix unsigned -childformat {{s0d -radix unsigned} {s1d -radix unsigned} {s2d -radix unsigned} {s3d -radix unsigned} {s4d -radix unsigned} {s5d -radix unsigned} {s6d -radix unsigned} {s7d -radix unsigned}} -subitemconfig {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/s0d {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/s1d {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/s2d {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/s3d {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/s4d {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/s5d {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/s6d {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/s7d {-radix unsigned}} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/1st_clk_compute_ixd
add wave -noupdate -group compute_score -radix unsigned -childformat {{ss0d -radix unsigned} {ss1d -radix unsigned} {ss2d -radix unsigned} {ss3d -radix unsigned}} -subitemconfig {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/ss0d {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/ss1d {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/ss2d {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/ss3d {-radix unsigned}} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/2nd_clk_compute_ixd
add wave -noupdate -group compute_score -radix unsigned -childformat {{sss0d -radix unsigned} {sss1d -radix unsigned}} -subitemconfig {/tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/sss0d {-radix unsigned} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/sss1d {-radix unsigned}} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/3rd_clk_compute_ixd
add wave -noupdate -group compute_score -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/sum_all_b
add wave -noupdate -group compute_score -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_score/sum_all_d
add wave -noupdate -height 17 -expand -group nms_core -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/line_1_7patch
add wave -noupdate -height 17 -expand -group nms_core -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/line_2_7patch
add wave -noupdate -height 17 -expand -group nms_core -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/line_3_7patch
add wave -noupdate -height 17 -expand -group nms_core -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/line_4_7patch
add wave -noupdate -height 17 -expand -group nms_core -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/line_5_7patch
add wave -noupdate -height 17 -expand -group nms_core -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/line_6_7patch
add wave -noupdate -height 17 -expand -group nms_core -radix unsigned /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/line_7_7patch
add wave -noupdate -height 17 -expand -group nms_core -color Pink /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/patch_7x7_vld
add wave -noupdate -height 17 -expand -group nms_core -color {Violet Red} /tb/u_FAST_with_NMS/u_fast_main_top/u_fast_fifo/xy_coord_vld
add wave -noupdate -height 17 -expand -group nms_core -radix unsigned /tb/u_FAST_with_NMS/u_NMS_top/x_coord_in
add wave -noupdate -height 17 -expand -group nms_core -radix unsigned /tb/u_FAST_with_NMS/u_NMS_top/y_coord_in
add wave -noupdate -height 17 -expand -group nms_core /tb/u_FAST_with_NMS/u_NMS_top/iscorner
add wave -noupdate -height 17 -expand -group nms_core -radix unsigned /tb/u_FAST_with_NMS/u_NMS_top/data_in
add wave -noupdate -height 17 -expand -group nms_core -radix unsigned /tb/u_FAST_with_NMS/u_NMS_top/x_coord_out
add wave -noupdate -height 17 -expand -group nms_core -radix unsigned /tb/u_FAST_with_NMS/u_NMS_top/y_coord_out
add wave -noupdate -height 17 -expand -group nms_core -radix unsigned /tb/u_FAST_with_NMS/u_NMS_top/corner_out
add wave -noupdate -height 17 -expand -group nms_core -radix unsigned /tb/u_FAST_with_NMS/u_NMS_top/1st_line
add wave -noupdate -height 17 -expand -group nms_core -radix unsigned /tb/u_FAST_with_NMS/u_NMS_top/2nd_line_nms_patch
add wave -noupdate -height 17 -expand -group nms_core -radix unsigned /tb/u_FAST_with_NMS/u_NMS_top/3rd_line_nms_patch
add wave -noupdate -height 17 -expand -group nms_core /tb/u_FAST_with_NMS/u_NMS_top/nms_vld
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1985000 ps} 1} {{Cursor 2} {1935000 ps} 1} {{Cursor 3} {1880204 ps} 0}
quietly wave cursor active 3
configure wave -namecolwidth 201
configure wave -valuecolwidth 271
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {1689605 ps} {2410792 ps}
